# Generated by Django 2.1.4 on 2022-11-02 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='task_id',
            field=models.CharField(default=None, max_length=500, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo',
            name='username',
            field=models.CharField(default=None, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
