# Generated by Django 2.1.4 on 2022-11-02 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_todo_reopen_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='task_id',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='todo',
            name='username',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='todo',
            unique_together={('username', 'task_id')},
        ),
    ]
